DROP TABLE IF EXISTS CREDENTIAL;
DROP TABLE IF EXISTS USR;

CREATE TABLE CREDENTIAL
(
  USER_ID bigint NOT NULL,
  CREDENTIAL_TYPE varchar(512) NOT NULL,
  CREDENTIAL_KEY varchar(2048),
  
  VALID_DATE timestamp,
  -- バージョン
  VER int,
  LAST_UPDATED_DATE timestamp,
  PRIMARY KEY (USER_ID, CREDENTIAL_TYPE)
);

CREATE TABLE USR
(
  USER_ID bigint NOT NULL,
  FIRST_NAME varchar(255),
  FAMILY_NAME varchar(255),
  LOGIN_ID varchar(32) UNIQUE,
  IS_LOGIN boolean,
  IS_ADMIN boolean,
  VER int,
  LAST_UPDATED_AT timestamp,
  PRIMARY KEY (USER_ID)
);

ALTER TABLE CREDENTIAL
  ADD FOREIGN KEY (USER_ID)
      REFERENCES USR (USER_ID)
      ON UPDATE RESTRICT
      ON DELETE RESTRICT;