cloud:
  aws:
    credentials:
      profile-name: msa-juku
      instance-profile: false
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-1
service:
  dns: http://localhost:8081